import { FaJava } from "react-icons/fa";
import {
  SiDocker,
  SiGit,
  SiKubernetes,
  SiNestjs,
  SiNginx,
  SiPython,
  SiReact,
  SiTailwindcss,
  SiTypescript,
  SiJavascript,
  SiNextdotjs,
  SiMongodb,
  SiPostgresql,
  SiRedis,
  SiAmazonwebservices,
  SiGooglecloud,
  SiJenkins,
  SiGithubactions,
  SiGraphql,
  SiPrisma,
  SiNodedotjs,
  SiAstro,
  SiMysql,
  SiSlack,
  SiNotion,
  SiDiscord,
  SiFigma,
  SiApachekafka,
  SiGoogle,
  SiFastapi,
  SiSpring,
  SiFirebase,
} from "react-icons/si";
import { stackTypeEnum, type Stack } from "~types/stack.type";

export const stacks: Stack[] = [
  {
    id: 1,
    stackType: stackTypeEnum.Enum.Frontend,
    name: "React",
    icon: SiReact,
    description: "컴포넌트 기반의 UI 라이브러리로 동적인 웹 애플리케이션 구축",
    color: "#61DAFB",
    featured: false,
  },
  {
    id: 2,
    stackType: stackTypeEnum.Enum.Backend,
    name: "NestJS",
    icon: SiNestjs,
    description: "TypeScript 기반의 확장 가능한 Node.js 서버 프레임워크",
    color: "#E0234E",
    featured: true,
    superFeatured: true,
  },
  {
    id: 3,
    stackType: stackTypeEnum.Enum.Backend,
    name: "Docker",
    icon: SiDocker,
    description: "컨테이너 기반 가상화로 일관된 개발 및 배포 환경 구성",
    color: "#2496ED",
    featured: true,
  },
  {
    id: 4,
    stackType: stackTypeEnum.Enum.DevOps,
    name: "Git",
    icon: SiGit,
    description: "분산 버전 관리 시스템으로 효율적인 협업과 코드 관리",
    color: "#F05032",
    featured: false,
  },
  {
    id: 5,
    stackType: stackTypeEnum.Enum.Backend,
    name: "Kubernetes",
    icon: SiKubernetes,
    description: "컨테이너 오케스트레이션으로 자동화된 배포 및 스케일링",
    color: "#326CE5",
    featured: false,
  },
  {
    id: 6,
    stackType: stackTypeEnum.Enum.Backend,
    name: "Nginx",
    icon: SiNginx,
    description: "고성능 웹 서버 및 리버스 프록시로 트래픽 관리",
    color: "#009639",
    featured: false,
  },
  {
    id: 7,
    stackType: stackTypeEnum.Enum.Backend,
    name: "Python",
    icon: SiPython,
    description: "범용 프로그래밍 언어로 데이터 처리 및 백엔드 개발",
    color: "#306998",
    featured: false,
  },
  {
    id: 8,
    stackType: stackTypeEnum.Enum.Frontend,
    name: "TailwindCSS",
    icon: SiTailwindcss,
    description: "유틸리티 우선 CSS 프레임워크로 빠른 UI 스타일링",
    color: "#06B6D4",
    featured: false,
  },
  {
    id: 9,
    stackType: stackTypeEnum.Enum.Frontend,
    name: "TypeScript",
    icon: SiTypescript,
    description: "정적 타입 지원으로 안정적인 JavaScript 개발",
    color: "#3178C6",
    featured: true,
    superFeatured: true,
  },
  {
    id: 10,
    stackType: stackTypeEnum.Enum.Frontend,
    name: "Next.js",
    icon: SiNextdotjs,
    description: "React 기반 프레임워크로 SSR 및 정적 사이트 생성",
    color: "#000000",
    featured: false,
  },
  {
    id: 11,
    stackType: stackTypeEnum.Enum.Backend,
    name: "MongoDB",
    icon: SiMongodb,
    description: "유연한 스키마의 NoSQL 데이터베이스",
    color: "#4DB33D",
    featured: false,
  },
  {
    id: 12,
    stackType: stackTypeEnum.Enum.Backend,
    name: "PostgreSQL",
    icon: SiPostgresql,
    description: "강력한 관계형 데이터베이스로 복잡한 쿼리 처리",
    color: "#4169E1",
    featured: false,
  },
  {
    id: 13,
    stackType: stackTypeEnum.Enum.Backend,
    name: "Redis",
    icon: SiRedis,
    description: "인메모리 데이터 스토어로 고성능 캐싱 구현",
    color: "#DD0031",
    featured: false,
  },
  {
    id: 14,
    stackType: stackTypeEnum.Enum.Backend,
    name: "AWS",
    icon: SiAmazonwebservices,
    description: "클라우드 컴퓨팅 서비스로 확장 가능한 인프라 구축",
    color: "#FF9900",
    featured: true,
  },
  {
    id: 15,
    stackType: stackTypeEnum.Enum.Backend,
    name: "GCP",
    icon: SiGooglecloud,
    description: "구글 클라우드 플랫폼으로 현대적인 클라우드 인프라 운영",
    color: "#4285F4",
    featured: false,
  },
  {
    id: 16,
    stackType: stackTypeEnum.Enum.DevOps,
    name: "Jenkins",
    icon: SiJenkins,
    description: "자동화된 CI/CD 파이프라인 구축 및 관리",
    color: "#DCDCDC",
    featured: false,
  },
  {
    id: 17,
    stackType: stackTypeEnum.Enum.DevOps,
    name: "GitHub Actions",
    icon: SiGithubactions,
    description: "GitHub 기반 워크플로우 자동화 및 CI/CD",
    color: "#2088FF",
    featured: false,
  },
  {
    id: 18,
    stackType: stackTypeEnum.Enum.Backend,
    name: "GraphQL",
    icon: SiGraphql,
    description: "효율적인 API 쿼리 언어로 최적화된 데이터 요청",
    color: "#E10098",
    featured: false,
  },
  {
    id: 19,
    stackType: stackTypeEnum.Enum.Backend,
    name: "Prisma",
    icon: SiPrisma,
    description: "타입 안전한 데이터베이스 ORM으로 효율적인 데이터 접근",
    color: "#3987C8",
    featured: false,
  },
  {
    id: 20,
    stackType: stackTypeEnum.Enum.Frontend,
    name: "JavaScript",
    icon: SiJavascript,
    description: "웹 브라우저에서 동작하는 동적 프로그래밍 언어",
    color: "#F7DF1E",
    featured: true,
  },
  {
    id: 21,
    stackType: stackTypeEnum.Enum.Backend,
    name: "Node.js",
    icon: SiNodedotjs,
    description: "확장 가능한 서버 사이드 JavaScript 런타임 환경",
    color: "#339933",
    featured: false,
  },
  {
    id: 22,
    stackType: stackTypeEnum.Enum.Frontend,
    name: "Astro",
    icon: SiAstro,
    description: "콘텐츠 중심의 고성능 웹사이트를 위한 최신 프레임워크",
    color: "#FF5A00",
    featured: true,
  },
  {
    id: 23,
    stackType: stackTypeEnum.Enum.Backend,
    name: "MySQL",
    icon: SiMysql,
    description: "신뢰성 높은 오픈소스 관계형 데이터베이스 시스템",
    color: "#4479A1",
    featured: true,
  },
  {
    id: 24,
    stackType: stackTypeEnum.Enum.DevOps,
    name: "Slack",
    icon: SiSlack,
    description: "실시간 커뮤니케이션과 협업을 위한 메시징 플랫폼",
    color: "#4A154B",
    featured: false,
  },
  {
    id: 25,
    stackType: stackTypeEnum.Enum.DevOps,
    name: "Notion",
    icon: SiNotion,
    description: "문서 작성과 지식 관리를 위한 올인원 워크스페이스",
    color: "#000000",
    featured: false,
  },
  {
    id: 26,
    stackType: stackTypeEnum.Enum.DevOps,
    name: "Discord",
    icon: SiDiscord,
    description:
      "음성, 채팅, 화면 공유 등 다양한 기능을 제공하는 커뮤니티 플랫폼",
    color: "#5865F2",
    featured: false,
  },
  {
    id: 27,
    stackType: stackTypeEnum.Enum.Frontend,
    name: "Figma",
    icon: SiFigma,
    description: "디자인 툴로 웹 및 모바일 앱 디자인 및 협업",
    color: "#F24E1E",
    featured: false,
  },
  {
    id: 28,
    stackType: stackTypeEnum.Enum.Backend,
    name: "Java",
    icon: FaJava,
    description: "객체 지향 프로그래밍 언어로 다양한 애플리케이션 개발",
    color: "#F89820",
    featured: true,
  },
  {
    id: 29,
    stackType: stackTypeEnum.Enum.Backend,
    name: "Kafka",
    icon: SiApachekafka,
    description: "빠르고 확장 가능한 메시지 브로커로 데이터 스트리밍 처리",
    color: "#231F20",
    featured: false,
  },
  {
    id: 30,
    stackType: stackTypeEnum.Enum.Backend,
    name: "gRPC",
    icon: SiGoogle,
    description:
      "구조화된 데이터 표현을 위한 이진 프로토콜로 데이터 표현 최적화",
    color: "#244C5A",
    featured: true,
  },
  {
    id: 31,
    stackType: stackTypeEnum.Enum.Backend,
    name: "FastAPI",
    icon: SiFastapi,
    description: "빠르고 효율적인 Python 웹 프레임워크로 최적화된 API 개발",
    color: "#009688",
    featured: false,
  },
  {
    id: 32,
    stackType: stackTypeEnum.Enum.Backend,
    name: "Spring",
    icon: SiSpring,
    description: "자바 기반의 프레임워크로 안정적인 애플리케이션 개발",
    color: "#6DB33D",
    featured: false,
  },
  {
    id: 33,
    stackType: stackTypeEnum.Enum.Backend,
    name: "Firebase",
    icon: SiFirebase,
    description:
      "실시간 데이터베이스와 클라우드 서비스로 빠른 애플리케이션 개발",
    color: "#FFCA28",
    featured: false,
  },
];
