import { FaBrain, FaJava } from "react-icons/fa";
import {
  SiDocker,
  SiGit,
  SiKubernetes,
  SiNestjs,
  SiNginx,
  SiReact,
  SiTailwindcss,
  SiTypescript,
  SiJavascript,
  SiNextdotjs,
  SiMongodb,
  SiPostgresql,
  SiRedis,
  SiAmazonwebservices,
  SiGooglecloud,
  SiJenkins,
  SiGithubactions,
  SiGraphql,
  SiPrisma,
  SiNodedotjs,
  SiAstro,
  SiMysql,
  SiSlack,
  SiNotion,
  SiDiscord,
  SiFigma,
  SiApachekafka,
  SiGoogle,
  SiFastapi,
  SiSpring,
  SiFirebase,
  SiRabbitmq,
  SiElasticsearch,
  SiKotlin,
  SiMariadb,
  SiOpenai,
  SiWearos,
  SiPython,
  SiShadcnui,
  SiRemix,
  SiLangchain,
  SiNaver,
  SiFlask,
  SiDjango,
} from "react-icons/si";
import { TbBrandReactNative } from "react-icons/tb";
import { stackTypeEnum, type Stack } from "~common/types/stack.type";

/**
 * ID 생성 규칙
 * XYZZ
 * X: TypeID
 * Frontend: 1
 * Backend: 2
 * DevOps: 3
 * ETC: 4
 *
 * YY: 기술 유형
 * 언어: 1
 * 프레임워크: 2
 * 데이터베이스: 3
 * 클라우드: 4
 * 툴: 5
 * 기타: 6
 *
 * ZZ: 01-99
 * 넘버링
 */
export const stacks: Stack[] = [
  // Frontend (1xxx) - 언어 (11xx)
  {
    id: 1101,
    stackType: [stackTypeEnum.Enum.Frontend, stackTypeEnum.Enum.Backend],
    name: "JavaScript",
    icon: SiJavascript,
    description: "웹 브라우저에서 동작하는 동적 프로그래밍 언어",
    color: "#F7DF1E",
    featured: true,
    superFeatured: false,
  },
  {
    id: 1102,
    stackType: [stackTypeEnum.Enum.Frontend, stackTypeEnum.Enum.Backend],
    name: "TypeScript",
    icon: SiTypescript,
    description: "정적 타입 지원으로 안정적인 JavaScript 개발",
    color: "#3178C6",
    featured: true,
    superFeatured: true,
  },

  // Frontend (1xxx) - 프레임워크 (12xx)
  {
    id: 1201,
    stackType: [stackTypeEnum.Enum.Frontend],
    name: "React",
    icon: SiReact,
    description: "컴포넌트 기반의 UI 라이브러리로 동적인 웹 애플리케이션 구축",
    color: "#61DAFB",
    featured: false,
    superFeatured: false,
  },
  {
    id: 1202,
    stackType: [stackTypeEnum.Enum.Frontend],
    name: "Next.js",
    icon: SiNextdotjs,
    description: "React 기반 프레임워크로 SSR 및 정적 사이트 생성",
    color: "#0070F3",
    featured: false,
    superFeatured: false,
  },
  {
    id: 1203,
    stackType: [stackTypeEnum.Enum.Frontend],
    name: "Astro",
    icon: SiAstro,
    description: "콘텐츠 중심의 고성능 웹사이트를 위한 최신 프레임워크",
    color: "#FF5A00",
    featured: true,
    superFeatured: false,
  },
  {
    id: 1204,
    stackType: [stackTypeEnum.Enum.Frontend],
    name: "TailwindCSS",
    icon: SiTailwindcss,
    description: "유틸리티 우선 CSS 프레임워크로 빠른 UI 스타일링",
    color: "#06B6D4",
    featured: false,
    superFeatured: false,
  },
  {
    id: 1205,
    stackType: [stackTypeEnum.Enum.Frontend],
    name: "Shadcn/UI",
    icon: SiShadcnui,
    description: "빠르고 편리한 UI 컴포넌트 라이브러리",
    color: "#000000",
    featured: false,
    superFeatured: false,
  },
  {
    id: 1206,
    stackType: [stackTypeEnum.Enum.Frontend],
    name: "Remix",
    icon: SiRemix,
    description: "React Router를 기반으로 구축된 오픈소스 react 프레임워크",
    color: "#000000",
    featured: false,
    superFeatured: false,
  },
  {
    id: 1207,
    stackType: [stackTypeEnum.Enum.Frontend],
    name: "React-Native",
    icon: TbBrandReactNative,
    description: "React를 사용하여 모바일 앱을 개발하기 위한 프레임워크",
    color: "#61DAFB",
    featured: false,
    superFeatured: false,
  },

  // Backend (2xxx) - 언어 (21xx)
  {
    id: 2101,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "Java",
    icon: FaJava,
    description: "객체 지향 프로그래밍 언어로 다양한 애플리케이션 개발",
    color: "#F89820",
    featured: true,
    superFeatured: true,
  },
  {
    id: 2102,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "Kotlin",
    icon: SiKotlin,
    description:
      "현대적이고 간결하며, 자바와 호환되는 정적 타입 지정 프로그래밍 언어",
    color: "#7F52FF",
    featured: true,
    superFeatured: true,
  },
  {
    id: 2103,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "Python",
    icon: SiPython,
    description: "범용 프로그래밍 언어로 데이터 처리 및 백엔드 개발",
    color: "#306998",
    featured: false,
    superFeatured: false,
  },

  // Backend (2xxx) - 프레임워크 (22xx)
  {
    id: 2201,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "NestJS",
    icon: SiNestjs,
    description: "TypeScript 기반의 확장 가능한 Node.js 서버 프레임워크",
    color: "#E0234E",
    featured: true,
    superFeatured: true,
  },
  {
    id: 2202,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "Spring",
    icon: SiSpring,
    description: "자바 기반의 프레임워크로 안정적인 애플리케이션 개발",
    color: "#6DB33D",
    featured: true,
    superFeatured: true,
  },
  {
    id: 2203,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "FastAPI",
    icon: SiFastapi,
    description: "빠르고 효율적인 Python 웹 프레임워크로 최적화된 API 개발",
    color: "#009688",
    featured: false,
    superFeatured: false,
  },
  {
    id: 2204,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "NodeJS",
    icon: SiNodedotjs,
    description: "확장 가능한 서버 사이드 JavaScript 런타임 환경",
    color: "#339933",
    featured: false,
    superFeatured: false,
  },
  {
    id: 2205,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "LangChain",
    icon: SiLangchain,
    description:
      "대규모 언어 모델(LLM)을 기반으로 애플리케이션을 구축하기 위한 오픈 소스 프레임워크",
    color: "#000000",
    featured: false,
    superFeatured: false,
  },
  {
    id: 2206,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "SpringAI",
    icon: FaBrain,
    description: "Spring 기반의 AI 프레임워크",
    color: "#6DB33D",
    featured: false,
    superFeatured: false,
  },
  {
    id: 2207,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "Flask",
    icon: SiFlask,
    description: "Python 기반의 웹 프레임워크",
    color: "#000000",
    featured: false,
    superFeatured: false,
  },
  {
    id: 2208,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "Django",
    icon: SiDjango,
    description: "Python 기반의 웹 프레임워크",
    color: "#02392b",
    featured: false,
    superFeatured: false,
  },

  // Backend (2xxx) - 데이터베이스 (23xx)
  {
    id: 2301,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "PostgreSQL",
    icon: SiPostgresql,
    description: "강력한 관계형 데이터베이스로 복잡한 쿼리 처리",
    color: "#4169E1",
    featured: false,
    superFeatured: false,
  },
  {
    id: 2302,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "MySQL",
    icon: SiMysql,
    description: "신뢰성 높은 오픈소스 관계형 데이터베이스 시스템",
    color: "#4479A1",
    featured: true,
    superFeatured: false,
  },
  {
    id: 2303,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "MariaDB",
    icon: SiMariadb,
    description: "MySQL과 호환되는 오픈소스 관계형 데이터베이스 관리 시스템",
    color: "#003545",
    featured: true,
    superFeatured: false,
  },
  {
    id: 2304,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "MongoDB",
    icon: SiMongodb,
    description: "유연한 스키마의 NoSQL 데이터베이스",
    color: "#4DB33D",
    featured: false,
    superFeatured: false,
  },
  {
    id: 2305,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "Redis",
    icon: SiRedis,
    description: "인메모리 데이터 스토어로 고성능 캐싱 구현",
    color: "#DD0031",
    featured: false,
    superFeatured: false,
  },
  {
    id: 2306,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "Weaviate",
    icon: SiWearos, // 임시 아이콘
    description:
      "벡터 데이터베이스로 AI 기반 의미론적 검색 및 추천 시스템 구축",
    color: "#005571",
    featured: false,
    superFeatured: false,
  },
  // Backend (2xxx) - 클라우드 (24xx)
  {
    id: 2401,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "AWS",
    icon: SiAmazonwebservices,
    description: "클라우드 컴퓨팅 서비스로 확장 가능한 인프라 구축",
    color: "#FF9900",
    featured: true,
    superFeatured: false,
  },
  {
    id: 2402,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "GCP",
    icon: SiGooglecloud,
    description: "구글 클라우드 플랫폼으로 현대적인 클라우드 인프라 운영",
    color: "#4285F4",
    featured: false,
    superFeatured: false,
  },
  {
    id: 2403,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "Firebase",
    icon: SiFirebase,
    description:
      "실시간 데이터베이스와 클라우드 서비스로 빠른 애플리케이션 개발",
    color: "#FFCA28",
    featured: false,
    superFeatured: false,
  },
  {
    id: 2404,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "NCP",
    icon: SiNaver,
    description: "네이버 클라우드가 제공하는 기업용 클라우드 서비스",
    color: "#00C853",
    featured: false,
    superFeatured: false,
  },

  // Backend (2xxx) - 툴 (25xx)
  {
    id: 2501,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "Docker",
    icon: SiDocker,
    description: "컨테이너 기반 가상화로 일관된 개발 및 배포 환경 구성",
    color: "#2496ED",
    featured: true,
    superFeatured: false,
  },
  {
    id: 2502,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "Kubernetes",
    icon: SiKubernetes,
    description: "컨테이너 오케스트레이션으로 자동화된 배포 및 스케일링",
    color: "#326CE5",
    featured: false,
    superFeatured: false,
  },
  {
    id: 2503,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "Nginx",
    icon: SiNginx,
    description: "고성능 웹 서버 및 리버스 프록시로 트래픽 관리",
    color: "#009639",
    featured: false,
    superFeatured: false,
  },
  {
    id: 2504,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "GraphQL",
    icon: SiGraphql,
    description: "효율적인 API 쿼리 언어로 최적화된 데이터 요청",
    color: "#E10098",
    featured: false,
    superFeatured: false,
  },
  {
    id: 2505,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "Prisma",
    icon: SiPrisma,
    description: "타입 안전한 데이터베이스 ORM으로 효율적인 데이터 접근",
    color: "#3987C8",
    featured: false,
    superFeatured: false,
  },
  {
    id: 2506,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "Kafka",
    icon: SiApachekafka,
    description: "빠르고 확장 가능한 메시지 브로커로 데이터 스트리밍 처리",
    color: "#231F20",
    featured: false,
    superFeatured: false,
  },
  {
    id: 2507,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "gRPC",
    icon: SiGoogle,
    description:
      "구조화된 데이터 표현을 위한 이진 프로토콜로 데이터 표현 최적화",
    color: "#244C5A",
    featured: true,
    superFeatured: false,
  },
  {
    id: 2508,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "RabbitMQ",
    icon: SiRabbitmq,
    description: "메시지 브로커로 데이터 스트리밍 처리",
    color: "#FF6600",
    featured: false,
    superFeatured: false,
  },
  {
    id: 2509,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "Elasticsearch",
    icon: SiElasticsearch,
    description: "데이터 검색 및 분석을 위한 오픈소스 검색 엔진",
    color: "#005571",
    featured: false,
    superFeatured: false,
  },
  {
    id: 2510,
    stackType: [stackTypeEnum.Enum.Backend],
    name: "OpenAI",
    icon: SiOpenai,
    description:
      "GPT, DALL-E, Whisper 등 다양한 AI 모델을 제공하는 OpenAI의 API 플랫폼",
    color: "#000000",
    featured: false,
    superFeatured: false,
  },

  // DevOps (3xxx) - 툴 (35xx)
  {
    id: 3501,
    stackType: [stackTypeEnum.Enum.DevOps],
    name: "Git",
    icon: SiGit,
    description: "분산 버전 관리 시스템으로 효율적인 협업과 코드 관리",
    color: "#F05032",
    featured: false,
    superFeatured: false,
  },
  {
    id: 3502,
    stackType: [stackTypeEnum.Enum.DevOps],
    name: "Jenkins",
    icon: SiJenkins,
    description: "자동화된 CI/CD 파이프라인 구축 및 관리",
    color: "#DCDCDC",
    featured: false,
    superFeatured: false,
  },
  {
    id: 3503,
    stackType: [stackTypeEnum.Enum.DevOps],
    name: "GitHub-Actions",
    icon: SiGithubactions,
    description: "GitHub 기반 워크플로우 자동화 및 CI/CD",
    color: "#2088FF",
    featured: false,
    superFeatured: false,
  },
  {
    id: 3504,
    stackType: [stackTypeEnum.Enum.DevOps, stackTypeEnum.Enum.ETC],
    name: "Slack",
    icon: SiSlack,
    description: "실시간 커뮤니케이션과 협업을 위한 메시징 플랫폼",
    color: "#4A154B",
    featured: false,
    superFeatured: false,
  },

  // ETC (4xxx) - 기타 (46xx)
  {
    id: 4601,
    stackType: [stackTypeEnum.Enum.ETC],
    name: "Notion",
    icon: SiNotion,
    description: "문서 작성과 지식 관리를 위한 올인원 워크스페이스",
    color: "#9B59B6",
    featured: false,
    superFeatured: false,
  },
  {
    id: 4602,
    stackType: [stackTypeEnum.Enum.ETC],
    name: "Discord",
    icon: SiDiscord,
    description:
      "음성, 채팅, 화면 공유 등 다양한 기능을 제공하는 커뮤니티 플랫폼",
    color: "#5865F2",
    featured: false,
    superFeatured: false,
  },
  {
    id: 4603,
    stackType: [stackTypeEnum.Enum.ETC],
    name: "Figma",
    icon: SiFigma,
    description: "디자인 툴로 웹 및 모바일 앱 디자인 및 협업",
    color: "#F24E1E",
    featured: false,
    superFeatured: false,
  },
];
